#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : crcmod
Version  : 1.7
Release  : 26
URL      : http://pypi.debian.net/crcmod/crcmod-1.7.tar.gz
Source0  : http://pypi.debian.net/crcmod/crcmod-1.7.tar.gz
Summary  : CRC Generator
Group    : Development/Tools
License  : MIT
Requires: crcmod-license = %{version}-%{release}
Requires: crcmod-python = %{version}-%{release}
Requires: crcmod-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
===========================
crcmod for Calculating CRCs
===========================

%package license
Summary: license components for the crcmod package.
Group: Default

%description license
license components for the crcmod package.


%package python
Summary: python components for the crcmod package.
Group: Default
Requires: crcmod-python3 = %{version}-%{release}

%description python
python components for the crcmod package.


%package python3
Summary: python3 components for the crcmod package.
Group: Default
Requires: python3-core
Provides: pypi(crcmod)

%description python3
python3 components for the crcmod package.


%prep
%setup -q -n crcmod-1.7
cd %{_builddir}/crcmod-1.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582914022
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/crcmod
cp %{_builddir}/crcmod-1.7/LICENSE %{buildroot}/usr/share/package-licenses/crcmod/3eb0123465010ad9f22c49106e26776969c7bcb2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/crcmod/3eb0123465010ad9f22c49106e26776969c7bcb2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
